### ISSUE TITLE
[Ques] 

### ISSUE THREAD

**Issue by Harshalrathore007** [rusty-electron/dotfiles#2]
Which script is being used for this thing
![image](https://user-images.githubusercontent.com/86074299/147399911-4edfc97b-2e57-46bb-8299-02c65d6a9e81.png)

**Comment by rusty-electron** [comment]
The tool is `conky` and similar to statusbar you can use in-built fields or even custom scripts. You can find the config [here](https://github.com/rusty-electron/dotfiles/blob/master/.config/conky/conky.conf). It has a `conky.config` variable that stores the settings (font, alignments, colour, gaps, etc). In `conky.text` you can set what is displayed on the conky display space, as you can see I have uptime, cpu freq, usage, networking up/down graph and a custom command that reads a local file to show its contents as a todo list).

Some helpful links:
* [github page](https://github.com/brndnmtthws/conky)
* [example configs](https://github.com/brndnmtthws/conky/wiki/Configs)
* [settings](http://conky.sourceforge.net/config_settings.html)
* [variables](http://conky.sourceforge.net/variables.html)

**Comment by rusty-electron** [comment]
closing due to age
