### ISSUE TITLE
[Ques]

### ISSUE THREAD

**Issue by Aditya190600** [rusty-electron/dotfiles#3]
Hey,
How are you auto-starting terminal without facing any issue with X Server

**Comment by rusty-electron** [comment]
Hi @Aditya190600, are you refering to this section of the code in `.xprofile`?
https://github.com/rusty-electron/dotfiles/blob/0c4c3dfaa09ee11b8b2d975aaed573d390b17db4/.xprofile#L18-L21

**Comment by Aditya190600** [comment]
Not this ...
It's related to starting terminal without facing any issues as such with Xserver

I put 
`startx` in the .bashrc file and face issues while trying to ssh and start a new terminal

So I wanted to know what you did to mitigate that warning prompt @rusty-electron 

This is the warning I get
`/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server`

**Comment by rusty-electron** [comment]
Ok, i get it now.

You should add this snippet in your `.bash_profile`/`.zprofile`
```bash
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
```
Source: [archwiki article](https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login)

You do not find this in my `.bash_profile` as I am using a login manager.

**Comment by rusty-electron** [comment]
closing due to age
